### ISSUE TITLE
Adopt a cleaner project layout

### ISSUE THREAD

**Issue by demberto** [ProfessorUdGuru/toykinter#1]
- Replace the `app/python` dir with a `toykinter` dir.
- Rename `main.py` to `__main__.py` to make it invokable from python like a module, e.g.
  ```
  python -m toykinter
  ```
- Add a `__init__.py` file in the renamed `toykinter` folder.
- Use relative imports.

**Comment by ProfessorUdGuru** [comment]
Thanks for the suggestions. I don't have time to polish this repo, I'm working 24/7 on my Treebard repo where these widgets are actually used. Toykinter is useful code for somebody, but I think the right way to rewrite ttk widgets is to go back to the tcl/TK and work with the original code as done by the creators of Tkinter.

**Comment by ProfessorUdGuru** [comment]
Since you're interested in the Combobox, the version in the Treebard repo is probably more current. I think I moved it to the widgets.py module. It's a superior widget to the ttk.Combobox but it logs down with large value lists.

**Comment by demberto** [comment]
I will check that out.
